name: Auto Deploy Energi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Auto commit and push
        run: |
          git config --global user.email "chatgpt@energi.ai"
          git config --global user.name "Energi Bot"
          git add .
          git commit -m "Auto update by bot — v.2507222001"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/adenauj-energi/energi-site.git HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
